"""
visualizer.py
=============
Serializes a TRUSTMETER result into:

  1. output/gverify.js    - a plain JS data module (CommonJS-compatible)
                              containing the gauge + radar chart data for a
                              article under review and an illustrative sample.

  2. output/dashboard.html - a self-contained Chart.js page (data inlined,
                              no dependency on gverify.js) that actually
                              renders the Gauge Chart + Radar Chart, so the
                              JS payload is demonstrably correct rather than
                              inert data nobody looks at.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from . import config
from .pipeline import RADAR_CATEGORIES, AnalysisResult

GAUGE_ZONES = [
    {"max": 39, "color": "#B64A3A", "label": "Low Credibility"},
    {"max": 59, "color": "#C08A1E", "label": "Needs Verification"},
    {"max": 79, "color": "#55916F", "label": "Generally Credible"},
    {"max": 100, "color": "#1E7A46", "label": "High Credibility"},
]


def _article_payload(result: AnalysisResult) -> dict:
    return {
        "headline": result.headline,
        "url": result.url,
        "domain": result.domain,
        "sourceStatus": result.reputation.status,
        "finalTrustScore": result.final_trust_score,
        "verdict": result.verdict,
        "radarProfile": [result.radar_profile[c] for c in RADAR_CATEGORIES],
        "breakdown": {
            "clickbaitScore": result.clickbait.score,
            "sourceScore": result.reputation.score,
            "lexicalDiversityScore": result.lexical.diversity_trust_score,
        },
    }


def build_gverify_payload(suspicious: AnalysisResult, baseline: AnalysisResult) -> dict:
    return {
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "radarCategories": RADAR_CATEGORIES,
        "gaugeZones": GAUGE_ZONES,
        "articleUnderReview": _article_payload(suspicious),
        "referenceSample": _article_payload(baseline),
    }


def export_gverify_js(
    suspicious: AnalysisResult,
    baseline: AnalysisResult,
    path: Optional[Path] = None,
) -> Path:
    """Write the TRUSTMETER signal payload to output/gverify.js."""
    path = path or config.GVERIFY_JS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    payload = build_gverify_payload(suspicious, baseline)
    js_object = json.dumps(payload, indent=2)

    contents = f"""// gverify.js — auto-generated by the TRUSTMETER analyzer.
// Do not hand-edit; regenerate via `python main.py --url ... ` or `--demo`.
// Consumed by output/dashboard.html to render the Gauge Chart + Radar Chart.

const gverifyData = {js_object};

if (typeof module !== "undefined" && module.exports) {{
  module.exports = gverifyData;
}}
"""
    path.write_text(contents, encoding="utf-8")
    return path


def export_dashboard_html(
    suspicious: AnalysisResult,
    baseline: AnalysisResult,
    path: Optional[Path] = None,
) -> Path:
    """
    Write a self-contained HTML dashboard that renders the same payload as
    gverify.js via Chart.js (Gauge + Radar), with data inlined so the file
    works standalone with no local file-loading step required.
    """
    path = path or config.DASHBOARD_HTML_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    payload = build_gverify_payload(suspicious, baseline)
    payload_json = json.dumps(payload, indent=2)

    html = _DASHBOARD_TEMPLATE.replace("__GVERIFY_DATA__", payload_json)
    path.write_text(html, encoding="utf-8")
    return path


_DASHBOARD_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>TRUSTMETER — Credibility Assessment</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.4/chart.umd.min.js"></script>
<style>
  :root {
    --ink: #1B1A17;
    --paper: #F6F4EF;
    --panel: #FFFFFF;
    --line: #E4E0D6;
    --accent-red: #C0392B;
    --accent-amber: #C08A1E;
    --accent-green: #1E7A46;
    --mono: "IBM Plex Mono", ui-monospace, "SF Mono", Menlo, monospace;
    --serif: "Source Serif 4", Georgia, "Times New Roman", serif;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--paper);
    color: var(--ink);
    font-family: var(--serif);
    line-height: 1.5;
  }
  header {
    padding: 2.5rem clamp(1.25rem, 4vw, 3rem) 1.5rem;
    border-bottom: 1px solid var(--line);
  }
  header .kicker {
    font-family: var(--mono);
    font-size: 0.72rem;
    letter-spacing: 0.04em;
    color: #6B6559;
    margin: 0 0 0.5rem;
  }
  header h1 {
    margin: 0;
    font-size: clamp(1.6rem, 3vw, 2.3rem);
    font-weight: 600;
    max-width: 24ch;
  }
  main {
    max-width: 1180px;
    margin: 0 auto;
    padding: 2rem clamp(1.25rem, 4vw, 3rem) 4rem;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
  }
  @media (max-width: 820px) { main { grid-template-columns: 1fr; } }
  .card {
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 4px;
    padding: 1.5rem;
  }
  .card h2 {
    font-family: var(--mono);
    font-size: 0.82rem;
    font-weight: 500;
    letter-spacing: 0.01em;
    margin: 0 0 0.9rem;
    color: #4A463D;
  }
  .article-meta {
    font-size: 0.92rem;
    color: #3C392F;
  }
  .article-meta .headline {
    font-weight: 600;
    font-size: 1.05rem;
    margin: 0 0 0.35rem;
  }
  .article-meta .domain {
    font-family: var(--mono);
    font-size: 0.78rem;
    color: #6B6559;
  }
  .gauge-wrap { grid-column: span 1; text-align: center; }
  .gauge-score {
    font-family: var(--mono);
    font-size: 2.6rem;
    font-weight: 600;
    margin-top: -3.2rem;
  }
  .gauge-verdict {
    font-family: var(--mono);
    font-size: 0.85rem;
    letter-spacing: 0.02em;
  }
  .verdict-reliable { color: var(--accent-green); }
  .verdict-caution { color: var(--accent-amber); }
  .verdict-misinformation { color: var(--accent-red); }
  .full-width { grid-column: 1 / -1; }
  .legend-row {
    display: flex;
    gap: 1.5rem;
    justify-content: center;
    margin-top: 0.75rem;
    font-family: var(--mono);
    font-size: 0.78rem;
    color: #6B6559;
  }
  .legend-row span.dot {
    display: inline-block;
    width: 9px; height: 9px;
    border-radius: 50%;
    margin-right: 0.4rem;
  }
  footer {
    text-align: center;
    font-family: var(--mono);
    font-size: 0.72rem;
    color: #9A9484;
    padding: 0 0 2.5rem;
  }
</style>
</head>
<body>

<header>
  <p class="kicker">TRUSTMETER / CREDIBILITY ASSESSMENT</p>
  <h1>Explainable signals, alongside an illustrative reference sample</h1>
</header>

<main>

  <div class="card article-meta">
    <h2>Article under review</h2>
    <p class="headline" id="susp-headline"></p>
    <p class="domain" id="susp-domain"></p>
  </div>

  <div class="card article-meta">
    <h2>Illustrative reference sample</h2>
    <p class="headline" id="base-headline"></p>
    <p class="domain" id="base-domain"></p>
  </div>

  <div class="card gauge-wrap">
    <h2>Credibility score — article under review</h2>
    <canvas id="gaugeSuspicious" height="180"></canvas>
    <div class="gauge-score" id="gaugeSuspiciousScore"></div>
    <div class="gauge-verdict" id="gaugeSuspiciousVerdict"></div>
  </div>

  <div class="card gauge-wrap">
    <h2>Credibility score — reference sample</h2>
    <canvas id="gaugeBaseline" height="180"></canvas>
    <div class="gauge-score" id="gaugeBaselineScore"></div>
    <div class="gauge-verdict" id="gaugeBaselineVerdict"></div>
  </div>

  <div class="card full-width">
    <h2>Linguistic profile — radar comparison</h2>
    <canvas id="radarChart" height="110"></canvas>
    <div class="legend-row">
      <span><span class="dot" style="background:#C0392B"></span>Article under review</span>
      <span><span class="dot" style="background:#1E7A46"></span>Illustrative reference sample</span>
    </div>
  </div>

</main>

<footer>Generated by TRUSTMETER · Scores estimate credibility from available signals and do not establish truth.</footer>

<script>
const gverifyData = __GVERIFY_DATA__;

function verdictClass(verdict) {
  if (verdict === "High Credibility" || verdict === "Generally Credible") return "verdict-reliable";
  if (verdict === "Needs Verification") return "verdict-caution";
  return "verdict-misinformation";
}

function zoneColor(score) {
  for (const zone of gverifyData.gaugeZones) {
    if (score <= zone.max) return zone.color;
  }
  return gverifyData.gaugeZones[gverifyData.gaugeZones.length - 1].color;
}

function drawGauge(canvasId, score) {
  const ctx = document.getElementById(canvasId);
  const zones = gverifyData.gaugeZones;
  const boundaries = [0, ...zones.map(z => z.max)];
  const segments = zones.map((z, i) => boundaries[i + 1] - boundaries[i]);
  const colors = zones.map(z => z.color);

  new Chart(ctx, {
    type: "doughnut",
    data: {
      datasets: [
        {
          data: segments,
          backgroundColor: colors,
          borderWidth: 0,
          circumference: 180,
          rotation: 270,
          cutout: "72%",
        },
        {
          // needle, rendered as a near-invisible slice pair using a plugin below
          data: [1],
          backgroundColor: "transparent",
          borderWidth: 0,
          circumference: 0,
          rotation: 0,
        },
      ],
    },
    options: {
      plugins: { legend: { display: false }, tooltip: { enabled: false } },
      events: [],
    },
    plugins: [{
      id: "needle-" + canvasId,
      afterDraw(chart) {
        const { ctx, chartArea } = chart;
        const cx = (chartArea.left + chartArea.right) / 2;
        const cy = chartArea.bottom;
        const radius = (chartArea.bottom - chartArea.top) * 0.88;
        const angle = Math.PI + (Math.min(100, Math.max(0, score)) / 100) * Math.PI;

        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate(angle);
        ctx.beginPath();
        ctx.moveTo(0, -4);
        ctx.lineTo(radius * 0.82, 0);
        ctx.lineTo(0, 4);
        ctx.closePath();
        ctx.fillStyle = "#1B1A17";
        ctx.fill();
        ctx.restore();

        ctx.save();
        ctx.beginPath();
        ctx.arc(cx, cy, 6, 0, Math.PI * 2);
        ctx.fillStyle = "#1B1A17";
        ctx.fill();
        ctx.restore();
      },
    }],
  });
}

function renderArticleMeta(prefix, article) {
  document.getElementById(prefix + "-headline").textContent = article.headline;
  document.getElementById(prefix + "-domain").textContent =
    article.domain + " · " + article.sourceStatus;
}

function renderGaugeLabels(prefix, article) {
  const scoreEl = document.getElementById("gauge" + prefix + "Score");
  const verdictEl = document.getElementById("gauge" + prefix + "Verdict");
  scoreEl.textContent = article.finalTrustScore.toFixed(1);
  scoreEl.style.color = zoneColor(article.finalTrustScore);
  verdictEl.textContent = article.verdict.toUpperCase();
  verdictEl.className = "gauge-verdict " + verdictClass(article.verdict);
}

renderArticleMeta("susp", gverifyData.articleUnderReview);
renderArticleMeta("base", gverifyData.referenceSample);
renderGaugeLabels("Suspicious", gverifyData.articleUnderReview);
renderGaugeLabels("Baseline", gverifyData.referenceSample);

drawGauge("gaugeSuspicious", gverifyData.articleUnderReview.finalTrustScore);
drawGauge("gaugeBaseline", gverifyData.referenceSample.finalTrustScore);

new Chart(document.getElementById("radarChart"), {
  type: "radar",
  data: {
    labels: gverifyData.radarCategories,
    datasets: [
      {
        label: "Article under review",
        data: gverifyData.articleUnderReview.radarProfile,
        borderColor: "#C0392B",
        backgroundColor: "rgba(192, 57, 43, 0.15)",
        pointBackgroundColor: "#C0392B",
      },
      {
        label: "Illustrative reference sample",
        data: gverifyData.referenceSample.radarProfile,
        borderColor: "#1E7A46",
        backgroundColor: "rgba(30, 122, 70, 0.15)",
        pointBackgroundColor: "#1E7A46",
      },
    ],
  },
  options: {
    scales: {
      r: {
        min: 0,
        max: 100,
        ticks: { stepSize: 20, backdropColor: "transparent" },
        grid: { color: "#E4E0D6" },
        angleLines: { color: "#E4E0D6" },
        pointLabels: { font: { family: "IBM Plex Mono, monospace", size: 11 } },
      },
    },
    plugins: { legend: { display: false } },
  },
});
</script>

</body>
</html>
"""
